import type { NewScholarship } from "@/lib/db/schema";

function daysFromNow(days: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

type SeedScholarship = Omit<NewScholarship, "id" | "createdAt" | "updatedAt" | "lastVerifiedAt"> & {
  daysAgoVerified: number;
};

export const scholarshipSeeds: SeedScholarship[] = [
  {
    slug: "daad-epos-postgraduate",
    name: "DAAD EPOS — Development-Related Postgraduate Courses",
    providerName: "Deutscher Akademischer Austauschdienst (DAAD)",
    universityName: null,
    degreeLevels: ["Master's"],
    subjects: ["Engineering", "Development", "Public Health", "Economics", "Governance"],
    summary:
      "Fully funded Master's scholarship for professionals from developing and emerging countries taking a development-related course in Germany.",
    overview: [
      "EPOS funds international professionals from developing and emerging countries to take a development-related Master’s degree in Germany. The scholarship is built around a fixed catalogue of roughly 30 postgraduate courses — public health, water management, energy, agriculture, economics and governance — taught in English or German at 38 universities.",
      "It is aimed at people already working in the public sector, at NGOs or in state-owned companies, who intend to return home afterwards. Selection weighs professional relevance and development impact as heavily as grades, which is why the work-experience evidence matters more here than in a purely academic scholarship.",
      "Funding runs for the full length of the course, 12 to 24 months, and includes a language course in Germany before studies begin.",
    ],
    applicationsPerYearLabel: "≈ 4,100 / year",
    placesAvailableLabel: "≈ 320",

    fundingType: "fully_funded",
    fundingAmountLabel: "€992/mo + travel",
    fundingAmountMin: "992",
    fundingAmountMax: "992",
    fundingCurrency: "EUR",
    coveredExpenses: ["Tuition", "Monthly stipend", "Travel", "Insurance", "Study allowance", "German course"],
    fundingBreakdown: [
      { label: "Tuition fees", value: "Covered in full", status: "covered" },
      { label: "Monthly stipend", value: "€992 / month", status: "covered" },
      { label: "Travel allowance", value: "Return flight, lump sum", status: "covered" },
      { label: "Health, accident & liability insurance", value: "Paid by DAAD", status: "covered" },
      { label: "Study & research allowance", value: "€460 one-off", status: "covered" },
      { label: "German language course", value: "2–6 months, pre-study", status: "covered" },
      { label: "Family allowance (spouse / children)", value: "Case by case", status: "partial" },
      { label: "Rent subsidy", value: "Not included", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €31,400",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: [
      "Nigeria", "India", "Pakistan", "Brazil", "Kenya", "Ghana", "Bangladesh", "Egypt", "Indonesia", "Vietnam",
    ],
    eligibleCountriesLabel: "137 countries · DAC list · Nigeria included",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Nationality", detail: "a country on the DAAD list of developing and emerging countries." },
      { title: "Degree", detail: "a completed Bachelor's (four years preferred) in a subject related to the course." },
      { title: "Work experience", detail: "at least two years, normally in the public sector, an NGO or a state-owned enterprise." },
      { title: "Language", detail: "IELTS 6.5 / TOEFL 90 for English courses, German B2 for German-taught courses." },
      { title: "Final grade", detail: "usually 2.5 or better on the German scale for engineering courses." },
      { title: "Degree age", detail: "your last degree should not be older than six years at application." },
    ],
    languageRequirements: [{ language: "English", test: "IELTS", minScore: "6.5" }],
    gpaRequirement: "2.5 or better, German scale (engineering courses)",
    gpaRequirementMaxGerman: "2.5",
    workExperienceRequirement: "2+ years, public sector / NGO / state-owned enterprise",
    workExperienceMinYears: "2",
    requiredDocuments: [
      { label: "Completed DAAD application form", note: "Downloaded from the portal, signed" },
      { label: "Motivation letter (max 2 pages)", note: "Must name the specific EPOS course" },
      { label: "Academic CV in DAAD format", note: "Tabular, dated, signed" },
      { label: "Degree certificate + transcript", note: "Certified translation if not EN/DE" },
      { label: "Proof of 2 years work experience", note: "Employer letters with dates and role" },
      { label: "Language certificate", note: "IELTS 6.5 / TOEFL 90 or German B2" },
      { label: "Two letters of recommendation", note: "One academic, one professional" },
      { label: "Admission or pre-selection letter", note: "From the host university, if issued" },
    ],

    openDate: daysFromNow(-113),
    closeDate: daysFromNow(11),
    isRollingDeadline: false,
    importantDatesExtra: [
      { label: "PRE-SELECTION RESULT", value: "January 2027" },
      { label: "COURSE STARTS", value: "September 2027" },
    ],

    studyLocationLabel: "38 German universities, course-specific",
    applicationMethodLabel: "DAAD portal, via the host university",
    applicationProcessNote: "EPOS applications go to the university running your course, not to DAAD directly.",
    applicationSteps: [
      { title: "Pick an EPOS course", dateLabel: "Now — before deadline", body: "EPOS funds a fixed list of development-related Master’s programmes. Choose the course first; each one runs its own deadline inside the DAAD window." },
      { title: "Assemble the document file", dateLabel: "2–3 weeks of work", body: "Certified translations are the usual bottleneck. Order them before you write the motivation letter, not after." },
      { title: "Submit on the DAAD portal", dateLabel: "By the closing date, 23:59 CEST", body: "Upload the complete file to the DAAD portal and post hard copies to the university if your course requires them. Late uploads are rejected without review." },
      { title: "University pre-selection", dateLabel: "Nov – Jan", body: "The host university ranks applicants and forwards its shortlist to DAAD. Some courses hold interviews at this stage." },
      { title: "DAAD selection and offer", dateLabel: "Feb – Apr", body: "DAAD confirms funding, then issues the scholarship contract for the following intake." },
    ],
    applicationProcess: "Apply via the host university's admission process; DAAD funding is confirmed after university pre-selection.",
    officialApplicationUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/",
    officialSources: [
      { tag: "DAAD", title: "EPOS programme page — official conditions", url: "daad.de/en/studying-in-germany/scholarships/epos" },
      { tag: "PDF", title: "Course catalogue — official (PDF)", url: "daad.de/medien/epos-courses.pdf" },
      { tag: "LIST", title: "DAAD list of eligible countries", url: "daad.de/en/eligible-countries" },
    ],

    status: "open",
    daysAgoVerified: 1,
  },

  {
    slug: "heinrich-boell-scholarship",
    name: "Heinrich Böll Foundation Scholarship",
    providerName: "Heinrich-Böll-Stiftung",
    universityName: null,
    degreeLevels: ["Master's", "PhD"],
    subjects: ["Social Sciences", "Politics"],
    summary: "Fully funded scholarship for Master's and PhD students who share the foundation's green, civic-minded values.",
    overview: [
      "The Heinrich Böll Foundation funds students across all subjects at German universities who demonstrate strong academic results and engagement in civic, ecological or democratic causes.",
      "Selection is values-based as much as academic: applicants write a political essay and are expected to show ongoing volunteer or civic engagement, not just grades.",
    ],
    applicationsPerYearLabel: "≈ 2,800 / year",
    placesAvailableLabel: "≈ 1,100",

    fundingType: "fully_funded",
    fundingAmountLabel: "€934/mo + tuition",
    fundingAmountMin: "934",
    fundingAmountMax: "934",
    fundingCurrency: "EUR",
    coveredExpenses: ["Tuition", "Monthly stipend", "Study costs allowance"],
    fundingBreakdown: [
      { label: "Tuition fees", value: "Covered in full", status: "covered" },
      { label: "Monthly stipend", value: "€934 / month", status: "covered" },
      { label: "Study costs allowance", value: "€300 / semester", status: "covered" },
      { label: "Health insurance supplement", value: "Case by case", status: "partial" },
    ],
    fundingTotalValueLabel: "≈ €22,400",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Academic record", detail: "top 30% of your cohort, or equivalent evidence of strong performance." },
      { title: "Civic engagement", detail: "ongoing involvement in ecological, democratic or human-rights causes." },
      { title: "Language", detail: "German B1 by the start of funding; English accepted at application stage." },
      { title: "Enrolment", detail: "admitted to or enrolled in a German degree programme." },
    ],
    languageRequirements: [{ language: "German", test: "Goethe / telc", minScore: "B1" }],
    gpaRequirement: "Top 30% of cohort",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "Online application form", note: "Via the foundation's portal" },
      { label: "Political/civic essay", note: "Max 2 pages, foundation-set prompt" },
      { label: "CV", note: "Tabular, with civic engagement highlighted" },
      { label: "Academic transcript", note: "Certified translation if not EN/DE" },
      { label: "Reference letter", note: "Academic or civic-engagement referee" },
    ],

    openDate: daysFromNow(-90),
    closeDate: daysFromNow(18),
    isRollingDeadline: false,
    importantDatesExtra: [
      { label: "INTERVIEW ROUND", value: "6–8 weeks after deadline" },
      { label: "DECISION", value: "≈ 3 months after deadline" },
    ],

    studyLocationLabel: "Any German university",
    applicationMethodLabel: "Foundation's own online portal",
    applicationProcessNote: "Applications go directly to the Heinrich Böll Foundation, not through your university.",
    applicationSteps: [
      { title: "Check enrolment status", dateLabel: "Before applying", body: "You must already be admitted to, or enrolled in, a German degree programme — this is not a pre-admission scholarship." },
      { title: "Write the civic essay", dateLabel: "1–2 weeks", body: "The essay carries real weight in selection; generic statements are the most common reason for rejection." },
      { title: "Submit online", dateLabel: "By the closing date", body: "The portal closes automatically at the deadline; there is no late-submission process." },
      { title: "Interview (if shortlisted)", dateLabel: "6–8 weeks later", body: "A panel interview covering your academic plans and civic engagement." },
    ],
    applicationProcess: "Apply directly through the foundation's online portal after securing university admission.",
    officialApplicationUrl: "https://www.boell.de/en/scholarships",
    officialSources: [
      { tag: "HBS", title: "Scholarship programme — official conditions", url: "boell.de/en/scholarships" },
      { tag: "FAQ", title: "Application FAQ", url: "boell.de/en/scholarships/faq" },
    ],

    status: "open",
    daysAgoVerified: 3,
  },

  {
    slug: "kaad-scholarship",
    name: "KAAD Scholarship for Developing Countries",
    providerName: "Katholischer Akademischer Ausländer-Dienst (KAAD)",
    universityName: null,
    degreeLevels: ["Master's", "PhD"],
    subjects: ["Any field"],
    summary: "Fully funded scholarship for students from developing countries with a Christian community reference, open to any field of study.",
    overview: [
      "KAAD supports students and researchers from Africa, Asia, Latin America and Eastern Europe across any academic field, with a preference for candidates likely to take leadership roles at home after graduating.",
      "A distinguishing requirement is a supporting reference from a local church partner organisation, reflecting KAAD's Catholic-affiliated mission — the scholarship itself is open regardless of the applicant's own faith.",
    ],
    applicationsPerYearLabel: "≈ 900 / year",
    placesAvailableLabel: "≈ 180",

    fundingType: "fully_funded",
    fundingAmountLabel: "€1,050/mo",
    fundingAmountMin: "1050",
    fundingAmountMax: "1050",
    fundingCurrency: "EUR",
    coveredExpenses: ["Monthly stipend", "Insurance", "German course"],
    fundingBreakdown: [
      { label: "Monthly stipend", value: "€1,050 / month", status: "covered" },
      { label: "Health insurance", value: "Paid by KAAD", status: "covered" },
      { label: "German language course", value: "Pre-study, several months", status: "covered" },
      { label: "Tuition fees", value: "Not applicable at public universities", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €25,200",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: ["Nigeria", "Kenya", "Ghana", "India", "Philippines", "Brazil", "Colombia"],
    eligibleCountriesLabel: "Selected developing countries · Nigeria included",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Nationality", detail: "a developing country as defined on the KAAD partner-country list." },
      { title: "Reference", detail: "a supporting letter from a recognised local church partner organisation." },
      { title: "Degree", detail: "a good first degree relevant to the intended Master's or PhD." },
      { title: "Language", detail: "German B2 or strong English, depending on the programme." },
      { title: "Work experience", detail: "2+ years preferred, not strictly required." },
    ],
    languageRequirements: [{ language: "German", test: "Goethe / telc", minScore: "B2" }],
    gpaRequirement: "Good degree, no fixed cutoff",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "2+ years preferred",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "Application form", note: "Via KAAD regional office" },
      { label: "Church partner reference letter", note: "Required, from a recognised local organisation" },
      { label: "CV", note: "Tabular, dated" },
      { label: "Degree certificate + transcript", note: "Certified translation if needed" },
      { label: "Motivation letter", note: "Explaining post-study return plans" },
    ],

    openDate: daysFromNow(-60),
    closeDate: daysFromNow(23),
    isRollingDeadline: false,
    importantDatesExtra: [{ label: "REGIONAL INTERVIEW", value: "4–6 weeks after deadline" }],

    studyLocationLabel: "Any German university",
    applicationMethodLabel: "KAAD regional office, then Bonn head office",
    applicationProcessNote: "Applications start at your KAAD regional partner office before going to the Bonn head office.",
    applicationSteps: [
      { title: "Contact your KAAD regional office", dateLabel: "First step", body: "KAAD works through regional partner offices — find yours before assembling documents, since requirements vary slightly by region." },
      { title: "Secure the church reference", dateLabel: "2–4 weeks", body: "This is the step most applicants underestimate; start early." },
      { title: "Submit the full file", dateLabel: "By the closing date", body: "Regional office forwards complete files to the Bonn head office for review." },
      { title: "Regional interview", dateLabel: "4–6 weeks later", body: "A panel interview, often held at or near the regional office." },
    ],
    applicationProcess: "Apply through your KAAD regional partner office; do not apply directly to the Bonn head office.",
    officialApplicationUrl: "https://www.kaad.de/en/",
    officialSources: [{ tag: "KAAD", title: "Scholarship conditions — official", url: "kaad.de/en/scholarships" }],

    status: "open",
    daysAgoVerified: 5,
  },

  {
    slug: "tum-sustainable-futures-grant",
    name: "TUM Sustainable Futures Grant",
    providerName: "Technische Universität München",
    universityName: "TU München",
    degreeLevels: ["Master's"],
    subjects: ["Sustainability", "Engineering"],
    summary: "Partial scholarship from TU München for Master's students in sustainability-focused engineering programmes.",
    overview: [
      "TUM's Sustainable Futures Grant is a merit-based partial award for admitted Master's students in sustainability, renewable energy and related engineering fields.",
      "Unlike the fully funded programmes on this list, this is a university-run top-up grant intended to reduce living costs alongside Germany's low or zero tuition, not to replace a blocked account entirely.",
    ],
    applicationsPerYearLabel: "≈ 600 / year",
    placesAvailableLabel: "≈ 45",

    fundingType: "partial",
    fundingAmountLabel: "€6,000/year",
    fundingAmountMin: "500",
    fundingAmountMax: "500",
    fundingCurrency: "EUR",
    coveredExpenses: ["Partial living costs"],
    fundingBreakdown: [
      { label: "Annual grant", value: "€6,000 / year, paid quarterly", status: "covered" },
      { label: "Tuition fees", value: "Not applicable (public university)", status: "not_covered" },
      { label: "Insurance", value: "Not included", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €12,000",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Admission", detail: "admitted to a TUM Master's programme in a sustainability-related field." },
      { title: "Academic record", detail: "strong Bachelor's grade, evaluated case by case." },
      { title: "Motivation", detail: "a short statement connecting your studies to sustainability outcomes." },
    ],
    languageRequirements: [{ language: "English", test: "IELTS", minScore: "6.5" }],
    gpaRequirement: "Strong Bachelor's grade, case by case",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "TUM admission confirmation", note: "Required before applying" },
      { label: "Motivation statement", note: "Max 1 page" },
      { label: "Bachelor's transcript", note: "Certified translation if needed" },
    ],

    openDate: daysFromNow(-45),
    closeDate: daysFromNow(26),
    isRollingDeadline: false,
    importantDatesExtra: [],

    studyLocationLabel: "TU München, Bavaria",
    applicationMethodLabel: "TUM scholarship portal",
    applicationProcessNote: "Open only to students who already hold a TUM admission offer.",
    applicationSteps: [
      { title: "Secure TUM admission", dateLabel: "Prerequisite", body: "This grant only opens to applicants who already have a confirmed admission offer to an eligible TUM Master's programme." },
      { title: "Submit the grant application", dateLabel: "By the closing date", body: "Short form plus a one-page motivation statement submitted through the TUM portal." },
      { title: "Decision", dateLabel: "≈ 6 weeks later", body: "TUM notifies successful applicants by email; grants are paid quarterly once enrolled." },
    ],
    applicationProcess: "Apply through the TUM scholarship portal after receiving your admission offer.",
    officialApplicationUrl: "https://www.tum.de/en/studies/financing/scholarships",
    officialSources: [{ tag: "TUM", title: "Scholarship page — official", url: "tum.de/en/studies/financing/scholarships" }],

    status: "open",
    daysAgoVerified: 4,
  },

  {
    slug: "deutschlandstipendium-rwth-aachen",
    name: "Deutschlandstipendium at RWTH Aachen",
    providerName: "RWTH Aachen University",
    universityName: "RWTH Aachen",
    degreeLevels: ["Bachelor", "Master's"],
    subjects: ["STEM"],
    summary: "Germany's national merit scholarship, administered locally by RWTH Aachen for STEM students.",
    overview: [
      "The Deutschlandstipendium is Germany's national merit scholarship: half funded by the federal government, half by private sponsors, and administered locally by each participating university.",
      "At RWTH Aachen it targets STEM students who combine strong grades with social or civic engagement, rather than academic performance alone.",
    ],
    applicationsPerYearLabel: "≈ 1,400 / year",
    placesAvailableLabel: "≈ 220",

    fundingType: "partial",
    fundingAmountLabel: "€300/mo",
    fundingAmountMin: "300",
    fundingAmountMax: "300",
    fundingCurrency: "EUR",
    coveredExpenses: ["Partial living costs"],
    fundingBreakdown: [
      { label: "Monthly stipend", value: "€300 / month, for one year", status: "covered" },
      { label: "Tuition fees", value: "Not applicable (public university)", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €3,600",
    fundingTotalPeriodLabel: "Total value over 12 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: "Already enrolled or admitted",
    eligibilityRequirements: [
      { title: "Enrolment", detail: "enrolled or admitted at RWTH Aachen." },
      { title: "Academic record", detail: "above-average grades for your cohort and semester." },
      { title: "Engagement", detail: "social, civic or extracurricular engagement strengthens the application." },
    ],
    languageRequirements: [{ language: "German", test: "Goethe / telc", minScore: "B2" }],
    gpaRequirement: "Merit-based, above cohort average",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "RWTH online application", note: "Via the university portal" },
      { label: "Transcript of records", note: "Current semester grades" },
      { label: "Short engagement statement", note: "Optional but strengthens the file" },
    ],

    openDate: daysFromNow(-40),
    closeDate: daysFromNow(29),
    isRollingDeadline: false,
    importantDatesExtra: [],

    studyLocationLabel: "RWTH Aachen, North Rhine-Westphalia",
    applicationMethodLabel: "RWTH Aachen scholarship portal",
    applicationProcessNote: "Renewable annually, subject to continued good academic standing.",
    applicationSteps: [
      { title: "Check current standing", dateLabel: "Before applying", body: "Only enrolled or admitted RWTH students are eligible; check your semester grade average first." },
      { title: "Submit online", dateLabel: "By the closing date", body: "Application, transcript and optional engagement statement through the RWTH portal." },
      { title: "Decision", dateLabel: "≈ 8 weeks later", body: "Selection committee reviews and notifies by email; funding starts the following semester." },
    ],
    applicationProcess: "Apply through the RWTH Aachen scholarship portal.",
    officialApplicationUrl: "https://www.rwth-aachen.de/cms/root/studium/im-studium/finanzierung/",
    officialSources: [{ tag: "RWTH", title: "Deutschlandstipendium page — official", url: "rwth-aachen.de/deutschlandstipendium" }],

    status: "open",
    daysAgoVerified: 6,
  },

  {
    slug: "erasmus-joint-master-mobility",
    name: "Erasmus Mundus Joint Master Scholarship",
    providerName: "European Commission",
    universityName: null,
    degreeLevels: ["Master's"],
    subjects: ["Multiple consortia"],
    summary: "Fully funded EU scholarship covering tuition and living costs for joint Master's programmes across several European universities.",
    overview: [
      "Erasmus Mundus Joint Master programmes are run by consortia of universities across at least two European countries, with students studying at two or three of them over the course.",
      "The scholarship is one of the most generous available to non-EU students: full tuition plus a substantial monthly allowance, though competition is high and courses are subject-specific.",
    ],
    applicationsPerYearLabel: "≈ 20,000 / year (all consortia)",
    placesAvailableLabel: "≈ 1,900",

    fundingType: "fully_funded",
    fundingAmountLabel: "€1,400/mo",
    fundingAmountMin: "1400",
    fundingAmountMax: "1400",
    fundingCurrency: "EUR",
    coveredExpenses: ["Tuition", "Monthly stipend", "Travel", "Insurance"],
    fundingBreakdown: [
      { label: "Tuition fees", value: "Covered in full", status: "covered" },
      { label: "Monthly stipend", value: "€1,400 / month", status: "covered" },
      { label: "Travel & installation allowance", value: "Lump sum, distance-based", status: "covered" },
      { label: "Insurance", value: "Covered by consortium policy", status: "covered" },
    ],
    fundingTotalValueLabel: "≈ €42,000",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities (non-EU quota per consortium)",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Degree", detail: "a completed Bachelor's relevant to the joint programme." },
      { title: "Mobility", detail: "willingness to study at 2–3 universities in different countries." },
      { title: "Language", detail: "programme-dependent; usually English IELTS 6.5+." },
      { title: "Application window", detail: "each consortium sets its own deadline and selection process." },
    ],
    languageRequirements: [{ language: "English", test: "IELTS", minScore: "6.5" }],
    gpaRequirement: "Good degree, consortium-dependent",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "Consortium application form", note: "Via the specific programme's portal" },
      { label: "Motivation letter", note: "Programme-specific" },
      { label: "Degree certificate + transcript", note: "Certified translation if needed" },
      { label: "Language certificate", note: "IELTS or equivalent" },
      { label: "Two reference letters", note: "Academic" },
    ],

    openDate: daysFromNow(-70),
    closeDate: daysFromNow(34),
    isRollingDeadline: false,
    importantDatesExtra: [{ label: "COURSE STARTS", value: "September following intake" }],

    studyLocationLabel: "2–3 universities across Europe, per consortium",
    applicationMethodLabel: "Individual consortium portal",
    applicationProcessNote: "Each joint Master's programme has its own consortium and application portal — this listing describes the general EU-wide funding rules.",
    applicationSteps: [
      { title: "Choose a joint Master's programme", dateLabel: "First step", body: "Browse the EU catalogue of Erasmus Mundus programmes and pick one matching your field; each has its own deadline and mobility route." },
      { title: "Apply to the consortium", dateLabel: "Programme-specific window", body: "Application goes to the consortium directly, not to the European Commission." },
      { title: "Selection and scholarship offer", dateLabel: "Programme-specific", body: "Consortia rank applicants and offer EU scholarships to top candidates automatically — no separate scholarship application is needed." },
    ],
    applicationProcess: "Apply directly to your chosen consortium; scholarship selection is automatic for top-ranked applicants.",
    officialApplicationUrl: "https://www.eacea.ec.europa.eu/scholarships/emjm-catalogue_en",
    officialSources: [{ tag: "EU", title: "Erasmus Mundus catalogue — official", url: "eacea.ec.europa.eu/scholarships/emjm-catalogue" }],

    status: "open",
    daysAgoVerified: 8,
  },

  {
    slug: "humboldt-research-fellowship",
    name: "Humboldt Research Fellowship for Postdocs",
    providerName: "Alexander von Humboldt Stiftung",
    universityName: null,
    degreeLevels: ["Postdoc"],
    subjects: ["All research fields"],
    summary: "Fully funded postdoctoral research fellowship for early-career researchers with a completed doctorate, open on a rolling basis.",
    overview: [
      "The Humboldt Research Fellowship funds postdoctoral researchers of any nationality to design and pursue their own long-term research project with a host researcher in Germany.",
      "Unlike course-based scholarships, this is an open-ended research grant: applicants choose their own host institution and supervisor, and applications are accepted year-round rather than in fixed rounds.",
    ],
    applicationsPerYearLabel: "≈ 1,900 / year",
    placesAvailableLabel: "≈ 500",

    fundingType: "fully_funded",
    fundingAmountLabel: "€2,670/mo",
    fundingAmountMin: "2670",
    fundingAmountMax: "2670",
    fundingCurrency: "EUR",
    coveredExpenses: ["Monthly stipend", "Travel", "Insurance", "Family supplement"],
    fundingBreakdown: [
      { label: "Monthly stipend", value: "€2,670 / month", status: "covered" },
      { label: "Travel allowance", value: "Lump sum", status: "covered" },
      { label: "Health insurance", value: "Covered", status: "covered" },
      { label: "Family supplement", value: "Available if applicable", status: "covered" },
    ],
    fundingTotalValueLabel: "≈ €64,000",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Doctorate", detail: "completed within the last four years at application." },
      { title: "Research proposal", detail: "an independent proposal agreed in outline with a German host researcher." },
      { title: "Publication record", detail: "evidence of independent research ability, e.g. peer-reviewed publications." },
      { title: "Language", detail: "English is sufficient; German is not required." },
    ],
    languageRequirements: [{ language: "English", test: "Self-declared", minScore: "Fluent" }],
    gpaRequirement: "Doctorate required",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Research record required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "Research proposal", note: "Agreed in outline with a host researcher" },
      { label: "Doctoral certificate", note: "Or proof of imminent completion" },
      { label: "Publication list", note: "With key papers attached" },
      { label: "Host researcher's letter of invitation", note: "Required before submission" },
      { label: "Two academic reference letters", note: "Including your doctoral supervisor" },
    ],

    openDate: daysFromNow(-365),
    closeDate: null,
    isRollingDeadline: true,
    importantDatesExtra: [{ label: "REVIEW CYCLE", value: "Three committee rounds per year" }],

    studyLocationLabel: "Any German research institution, applicant's choice",
    applicationMethodLabel: "Humboldt Foundation online portal",
    applicationProcessNote: "Rolling admissions — there is no fixed annual deadline, but review happens in three committee rounds a year.",
    applicationSteps: [
      { title: "Find and contact a host researcher", dateLabel: "1–3 months", body: "You approach a German researcher in your field directly and agree on a project outline before applying — this step usually takes the longest." },
      { title: "Prepare the research proposal", dateLabel: "2–4 weeks", body: "A detailed, independent proposal reviewed alongside your publication record." },
      { title: "Submit online", dateLabel: "Any time", body: "Applications are reviewed in the next available committee round after submission." },
      { title: "Committee decision", dateLabel: "≈ 4 months later", body: "An independent review committee assesses the proposal and academic record." },
    ],
    applicationProcess: "Apply online any time; the Foundation reviews applications in three committee rounds per year.",
    officialApplicationUrl: "https://www.humboldt-foundation.de/en/apply/sponsorship-programmes/humboldt-research-fellowship",
    officialSources: [{ tag: "AvH", title: "Fellowship conditions — official", url: "humboldt-foundation.de/en/apply/humboldt-research-fellowship" }],

    status: "open",
    daysAgoVerified: 10,
  },

  {
    slug: "max-planck-imprs-doctoral",
    name: "Max Planck IMPRS Doctoral Programme",
    providerName: "Max Planck Society",
    universityName: null,
    degreeLevels: ["PhD"],
    subjects: ["Natural Sciences"],
    summary: "PhD funding at Max Planck Institutes paid as a full TV-L 13 employment contract rather than a stipend.",
    overview: [
      "International Max Planck Research Schools (IMPRS) fund doctoral researchers at Max Planck Institutes in the natural sciences, structured as a paid employment contract rather than a scholarship stipend.",
      "Each IMPRS school covers a specific research area and is jointly run with a partner university, so applicants effectively join a structured doctoral programme with coursework alongside their research.",
    ],
    applicationsPerYearLabel: "≈ 3,000 / year (all schools)",
    placesAvailableLabel: "≈ 400",

    fundingType: "fully_funded",
    fundingAmountLabel: "Full TV-L 13 contract",
    fundingAmountMin: "1900",
    fundingAmountMax: "1900",
    fundingCurrency: "EUR",
    coveredExpenses: ["Salary", "Social security", "Insurance"],
    fundingBreakdown: [
      { label: "Salary (TV-L 13, 65%)", value: "≈ €1,900–2,300 / month net", status: "covered" },
      { label: "Social security & pension contributions", value: "Standard employee rate", status: "covered" },
      { label: "Health insurance", value: "Via statutory employee scheme", status: "covered" },
      { label: "Tuition fees", value: "Not applicable (employment contract)", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €52,000",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Degree", detail: "a Master's degree (or equivalent) in the natural sciences at application." },
      { title: "Research fit", detail: "your research interests must match an active group at the institute." },
      { title: "Language", detail: "English is sufficient for most schools; German is not required." },
      { title: "Grade", detail: "strong Master's results, typically 2.0 or better on the German scale." },
    ],
    languageRequirements: [{ language: "English", test: "Self-declared", minScore: "Fluent" }],
    gpaRequirement: "2.0 German scale or equivalent",
    gpaRequirementMaxGerman: "2.0",
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "IMPRS online application", note: "Via the specific school's portal" },
      { label: "Master's certificate or proof of imminent completion", note: "Certified translation if needed" },
      { label: "Statement of research interest", note: "Naming a potential supervising group" },
      { label: "Two academic reference letters", note: "Including your Master's supervisor" },
    ],

    openDate: daysFromNow(-100),
    closeDate: daysFromNow(42),
    isRollingDeadline: false,
    importantDatesExtra: [{ label: "INTERVIEW WEEK", value: "≈ 6 weeks after deadline"}],

    studyLocationLabel: "Max Planck Institute + partner university",
    applicationMethodLabel: "IMPRS school-specific portal",
    applicationProcessNote: "Each IMPRS school runs its own portal and interview week; this listing covers the shared funding structure.",
    applicationSteps: [
      { title: "Choose an IMPRS school", dateLabel: "First step", body: "Over 60 schools exist across Germany; pick one matching your research area before applying." },
      { title: "Submit the online application", dateLabel: "By the closing date", body: "Application, transcripts and research statement through the school's own portal." },
      { title: "Interview week", dateLabel: "≈ 6 weeks later", body: "Shortlisted candidates are invited to an in-person or virtual interview week with several research groups." },
      { title: "Offer and contract", dateLabel: "≈ 2 weeks after interviews", body: "Successful candidates receive a formal TV-L 13 employment contract from the institute." },
    ],
    applicationProcess: "Apply through the specific IMPRS school's portal; funding is a formal employment contract, not a stipend.",
    officialApplicationUrl: "https://www.imprs.mpg.de/",
    officialSources: [{ tag: "MPG", title: "IMPRS network — official", url: "imprs.mpg.de" }],

    status: "open",
    daysAgoVerified: 2,
  },

  {
    slug: "kit-study-completion-scholarship",
    name: "KIT Study Completion Scholarship",
    providerName: "Karlsruhe Institute of Technology",
    universityName: "KIT Karlsruhe",
    degreeLevels: ["Master's"],
    subjects: ["Engineering"],
    summary: "Short partial scholarship from KIT for students in their final two semesters who need funding to complete their degree.",
    overview: [
      "KIT's Study Completion Scholarship is a short-term, partial award aimed specifically at Master's students in engineering who are in their final two semesters and facing a funding gap before graduation.",
      "It is not designed as primary funding for a full degree — applicants must already be enrolled and on track to graduate within the funding period.",
    ],
    applicationsPerYearLabel: "≈ 300 / year",
    placesAvailableLabel: "≈ 60",

    fundingType: "partial",
    fundingAmountLabel: "€750/mo for 6 months",
    fundingAmountMin: "750",
    fundingAmountMax: "750",
    fundingCurrency: "EUR",
    coveredExpenses: ["Partial living costs"],
    fundingBreakdown: [
      { label: "Monthly stipend", value: "€750 / month, 6 months", status: "covered" },
      { label: "Tuition fees", value: "Not applicable (public university)", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €4,500",
    fundingTotalPeriodLabel: "Total value over 6 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: "Already enrolled at KIT",
    eligibilityRequirements: [
      { title: "Enrolment", detail: "enrolled at KIT, in your final two semesters of a Master's programme." },
      { title: "Academic progress", detail: "on-track credit completion — this is checked against your transcript." },
      { title: "Financial need", detail: "a short statement of why funding is needed to complete the degree." },
    ],
    languageRequirements: [{ language: "German", test: "Goethe / telc", minScore: "B2" }],
    gpaRequirement: "On-track credits, no fixed grade cutoff",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "KIT scholarship application form", note: "Via the student services portal" },
      { label: "Transcript of records", note: "Showing on-track credits" },
      { label: "Financial need statement", note: "Short, max 1 page" },
    ],

    openDate: daysFromNow(-30),
    closeDate: daysFromNow(20),
    isRollingDeadline: false,
    importantDatesExtra: [],

    studyLocationLabel: "KIT Karlsruhe, Baden-Württemberg",
    applicationMethodLabel: "KIT student services portal",
    applicationProcessNote: "Only open to KIT students already in their final two semesters.",
    applicationSteps: [
      { title: "Check final-semester status", dateLabel: "Before applying", body: "Confirm with your program coordinator that you're within your final two semesters of credits." },
      { title: "Submit application", dateLabel: "By the closing date", body: "Transcript, form and financial need statement via student services." },
      { title: "Decision", dateLabel: "≈ 4 weeks later", body: "Student services notifies by email; funding starts the following month if approved." },
    ],
    applicationProcess: "Apply through KIT student services after confirming final-semester status.",
    officialApplicationUrl: "https://www.sle.kit.edu/english/financing.php",
    officialSources: [{ tag: "KIT", title: "Study financing page — official", url: "sle.kit.edu/english/financing" }],

    status: "open",
    daysAgoVerified: 7,
  },

  {
    slug: "stiftung-der-deutschen-wirtschaft",
    name: "Stiftung der Deutschen Wirtschaft (sdw)",
    providerName: "sdw",
    universityName: null,
    degreeLevels: ["Bachelor", "Master's"],
    subjects: ["Business", "STEM"],
    summary: "Fully funded scholarship and mentoring programme for high-performing Bachelor's and Master's students in business and STEM.",
    overview: [
      "sdw combines a modest monthly stipend with an extensive non-material programme — mentoring, seminars and a professional network — aimed at students who combine strong grades with leadership potential.",
      "German language proficiency at C1 is expected, since the programme's seminars and mentoring network operate primarily in German.",
    ],
    applicationsPerYearLabel: "≈ 1,200 / year",
    placesAvailableLabel: "≈ 280",

    fundingType: "fully_funded",
    fundingAmountLabel: "€300/mo + programme",
    fundingAmountMin: "300",
    fundingAmountMax: "300",
    fundingCurrency: "EUR",
    coveredExpenses: ["Monthly stipend", "Seminars", "Mentoring"],
    fundingBreakdown: [
      { label: "Monthly stipend", value: "€300 / month", status: "covered" },
      { label: "Seminar & mentoring programme", value: "Fully covered", status: "covered" },
      { label: "Tuition fees", value: "Not applicable (public university)", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €7,200",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: "Enrolled at a German university",
    eligibilityRequirements: [
      { title: "Enrolment", detail: "enrolled at a German university in business or a STEM field." },
      { title: "Academic record", detail: "merit-based, above-average grades expected." },
      { title: "Language", detail: "German C1, since seminars run in German." },
      { title: "Leadership potential", detail: "demonstrated through extracurricular or professional activity." },
    ],
    languageRequirements: [{ language: "German", test: "Goethe / telc", minScore: "C1" }],
    gpaRequirement: "Merit-based, above cohort average",
    gpaRequirementMaxGerman: null,
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "Online application", note: "Via the sdw portal" },
      { label: "Transcript of records", note: "Current standing" },
      { label: "CV", note: "Highlighting leadership or extracurricular activity" },
      { label: "Motivation letter", note: "In German" },
    ],

    openDate: daysFromNow(-30),
    closeDate: daysFromNow(147),
    isRollingDeadline: false,
    importantDatesExtra: [],

    studyLocationLabel: "Any German university",
    applicationMethodLabel: "sdw online portal",
    applicationProcessNote: "Selection includes an assessment day alongside the written application.",
    applicationSteps: [
      { title: "Submit online", dateLabel: "By the closing date", body: "Application, transcript, CV and motivation letter (in German) via the sdw portal." },
      { title: "Written selection round", dateLabel: "≈ 4 weeks later", body: "A shortlist is drawn from the written applications." },
      { title: "Assessment day", dateLabel: "≈ 8 weeks later", body: "Shortlisted candidates attend an in-person assessment day with group exercises and interviews." },
    ],
    applicationProcess: "Apply through the sdw online portal; selection includes a group assessment day.",
    officialApplicationUrl: "https://www.sdw.org/",
    officialSources: [{ tag: "sdw", title: "Scholarship programme — official", url: "sdw.org/foerderung" }],

    status: "open",
    daysAgoVerified: 9,
  },

  {
    slug: "hu-berlin-elsa-neumann-grant",
    name: "Elsa-Neumann Doctoral Grant (Berlin)",
    providerName: "Humboldt-Universität zu Berlin",
    universityName: "HU Berlin",
    degreeLevels: ["PhD"],
    subjects: ["All fields"],
    summary: "Fully funded state doctoral grant for PhD candidates at Berlin universities, awarded twice a year.",
    overview: [
      "The Elsa-Neumann-Stipendium is the State of Berlin's doctoral grant, awarded to PhD candidates at Berlin universities across all fields, in two rounds per year.",
      "It is one of the most generous PhD stipends available in Germany, but rounds are competitive and each Berlin university nominates only a limited number of candidates.",
    ],
    applicationsPerYearLabel: "≈ 1,000 / year (2 rounds)",
    placesAvailableLabel: "≈ 150 / year",

    fundingType: "fully_funded",
    fundingAmountLabel: "€1,200/mo",
    fundingAmountMin: "1200",
    fundingAmountMax: "1200",
    fundingCurrency: "EUR",
    coveredExpenses: ["Monthly stipend", "Family supplement", "Research costs"],
    fundingBreakdown: [
      { label: "Monthly stipend", value: "€1,200 / month", status: "covered" },
      { label: "Family supplement", value: "Available if applicable", status: "covered" },
      { label: "Research cost allowance", value: "Modest annual allowance", status: "partial" },
      { label: "Tuition fees", value: "Not applicable (public university)", status: "not_covered" },
    ],
    fundingTotalValueLabel: "≈ €28,800",
    fundingTotalPeriodLabel: "Total value over 24 months",

    eligibleNationalities: "all",
    eligibleCountriesLabel: "All nationalities",
    countryOfResidenceRestriction: null,
    eligibilityRequirements: [
      { title: "Admission", detail: "accepted as a PhD candidate at a Berlin university, HU Berlin included." },
      { title: "Academic record", detail: "top-tier Master's results, typically 1.5 German scale or better." },
      { title: "Nomination", detail: "your doctoral supervisor or faculty must nominate you for the round." },
      { title: "Timing", detail: "usually within the first two years of doctoral study." },
    ],
    languageRequirements: [{ language: "German or English", test: "Self-declared", minScore: "Fluent" }],
    gpaRequirement: "1.5 German scale or equivalent",
    gpaRequirementMaxGerman: "1.5",
    workExperienceRequirement: "Not required",
    workExperienceMinYears: "0",
    requiredDocuments: [
      { label: "Faculty nomination", note: "Required — you cannot self-apply without it" },
      { label: "Doctoral research exposé", note: "Outline of your PhD project" },
      { label: "Master's certificate + transcript", note: "Certified translation if needed" },
      { label: "Supervisor's reference letter", note: "Confirming doctoral supervision" },
    ],

    openDate: daysFromNow(-200),
    closeDate: daysFromNow(-2),
    isRollingDeadline: false,
    importantDatesExtra: [{ label: "NEXT ROUND OPENS", value: "April of the following year" }],

    studyLocationLabel: "Any Berlin university",
    applicationMethodLabel: "Via faculty nomination, HU Berlin doctoral office",
    applicationProcessNote: "You cannot apply directly — your faculty or supervisor must nominate you for the round.",
    applicationSteps: [
      { title: "Secure a faculty nomination", dateLabel: "Before the round opens", body: "Speak to your doctoral supervisor early; faculties have internal deadlines ahead of the university-wide one." },
      { title: "Submit the research exposé", dateLabel: "With the nomination", body: "A clear, well-scoped outline of your doctoral project strengthens the nomination significantly." },
      { title: "University review", dateLabel: "≈ 6 weeks after round closes", body: "HU Berlin's doctoral office reviews all faculty nominations and ranks candidates for the state-level award." },
    ],
    applicationProcess: "Ask your doctoral supervisor to nominate you before the round closes — self-application is not possible.",
    officialApplicationUrl: "https://www.hu-berlin.de/en/career/graduates/nafoeg-en",
    officialSources: [{ tag: "HU", title: "Elsa-Neumann-Stipendium — official", url: "hu-berlin.de/en/career/graduates/nafoeg-en" }],

    status: "closed",
    daysAgoVerified: 12,
  },
];
